apiVersion: apps/v1
kind: Deployment
metadata:
  name: static-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: static-web
  template:
    metadata:
      labels:
        app: static-web
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 80
          volumeMounts:
            - name: static-content
              mountPath: /usr/share/nginx/html
              readOnly: true
      volumes:
        - name: static-content
          persistentVolumeClaim:
            claimName: static-web-pv
